import Head from "next/head";
import { Bai_Jamjuree } from "@next/font/google";
import Hero from "@/components/Hero";

const fontPrimary = Bai_Jamjuree({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={fontPrimary.className}>
        <div className="main-holder">
          <section>
            <Hero />
          </section>
        </div>
      </main>
    </>
  );
}

// 1. hero for desktop version
