import Head from "next/head";
import { Bai_Jamjuree } from "@next/font/google";
import Hero from "@/components/Hero";
import Focus from "@/components/Focus";
import Data from "../assets/data/focusdata.json";
import { useEffect, useState } from "react";
import Feature from "@/components/Feature";

import Devices from "../assets/images/image-devices.png";
import Image from "next/image";

const fontPrimary = Bai_Jamjuree({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export default function Home() {
  const myData = Data;
  // const [myData, setMyData] = useState([]);
  // useEffect(() => {
  //   setMyData(Data);
  // }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={fontPrimary.className}>
        <div className="main-holder">
          <section>
            <Hero />
          </section>
          <section>
            <Focus data={myData[0]} />
          </section>
          <section>
            <Feature data={myData} />
          </section>
          <section>
            <Focus data={myData[1]} />
            <Image className="device flow-only" src={Devices} alt="device" />
          </section>
          <section>
            <Focus data={myData[2]} />
          </section>
        </div>
      </main>
    </>
  );
}

// 1. listing
