import { Bai_Jamjuree } from "@next/font/google";
import Head from "next/head";
import Hero from "@/components/Hero";
import Focus from "@/components/Focus";
import Feature from "@/components/Feature";
import Service from "@/components/Service";
import Image from "next/image";

import Data from "../assets/data/focusdata.json";
import Devices from "../assets/images/image-devices.png";
import Company from "@/components/Company";
import Action from "@/components/Action";
import { Main } from "next/document";
import Footer from "@/components/Footer";

const fontPrimary = Bai_Jamjuree({
  weight: ["400", "600"],
  subsets: ["latin"],
});

export default function Home() {
  const myData = Data;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={fontPrimary.className}>
        <div className="main-holder">
          <section>
            <Hero />
          </section>
          <section className="focus-flow flow-only">
            <Focus data={myData[0]} />
          </section>
          <section>
            <Feature data={myData} />
          </section>
          <section>
            <Focus data={myData[1]} />
            <Image className="device flow-only" src={Devices} alt="device" />
          </section>
          <section>
            <Focus data={myData[2]} />
          </section>
          <section>
            <Service data={myData} />
          </section>
          <section>
            <Company />
          </section>
          <section>
            <Action />
          </section>
        </div>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}

// 1. footer
